### ISSUE TITLE
[Android Bootcamp] Project 3: Grid Image Search - Ready for Review

### ISSUE THREAD

**Issue by lwhsu** [lwhsu/GridImageSearch#1]
My app is complete, please review.
Thanks!

/cc @nidhi1608 @thecodepath

Li-Wen Hsu lwhsu@yahoo-inc.com

**Comment by lwhsu** [comment]
BTW, I have a question here, in the video walk through, it said we should make "Full Image Display Activity" a child activity of "Search Activity", why we have to do that?  I do not really understand the reason.  And I found the Intent(s) passing between "Setting Activity" and "Search Activity" are fine, but "Setting Activity" is child to no one.

/cc @nidhi1608 @thecodepath

**Comment by nidhi1608** [comment]
Here child activity is just a conceptual term. Activities are independent entities in android. Here, "SearchActivity" is your master activity and "FullImageDisplayActivity" is the detail or child activity. To make it simpler, you can think of an email client where the email list is the master activity and the email body is the detail or child activity. "SettingActivity" is the place where you specify search filters and doesn't really have a parent-child relationship with other activities.

**Comment by lwhsu** [comment]
Thanks, I can understand the relationship between these activities.  However, what's the difference if we set "SearchActivity" and "FullImageDisplayActivity" as parent-child or not?

**Comment by nidhi1608** [comment]
Can you point me to the time in the video so I can get a reference to it?

**Comment by lwhsu** [comment]
Starting at http://vimeo.com/70808495 1:04:00, thanks.

**Comment by nidhi1608** [comment]
Thanks Li-wen. The parent-child relationship is set to provide up navigation in your app. The up navigation is presented in the Action Bar as shown below. 

![alt tag](http://developer.android.com/images/training/implementing-navigation-up.png)

Upon tapping Up, the user should be taken to the parent screen in the hierarchy. Without specifying that relationship, 'FullImageDisplayActivity' will not have any way to go back to the  'SearchActivity' except by pressing the back button. By specifying `android:parentActivityName` attribute in the `<activity>` element you are declaring the logical parent of 'FullImageDisplayActivity' to 'SearchActivity' so that the up navigation can be provided. Check out this guide on [Providing Proper Navigation](http://guides.codepath.com/android/Navigation-and-Task-Stacks#providing-proper-navigation) for more details.

**Comment by nidhi1608** [comment]
:+1: Your app looks good overall. I have provided a detailed [Feedback Guide here](https://gist.github.com/nesquena/44091e4727b154d04269) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be very important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
